name: ci-sjRW

on:
  push:
    branches: [ main ]

env:
  SLACK_USERNAME: ci failure notification
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.0'

      - name: OS Version
        run: cat /etc/os-release

      - name: Go Version
        run: go version

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3

      - name: Go Build
        run: |
          go build -v ./...

      - name: Go Test
        run: go test -v .


      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
            SLACK_TITLE: CI / Failure
            SLACK_COLOR: danger
            SLACK_MESSAGE: ci failed!!!