name: ci

on:
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.19.0'

      - name: OS Version
        run: cat /etc/os-release

      - name: Go Version
        run: go version

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3

      - name: Go Build
        run: |
          go build -v ./...

      - name: Go Test
        run: go test -v .