name: build-test-SJRW

on:
  push:
    branches: [ main ]
    paths: ['**/*.go', '**/**/*/yml'] # goファイル, ymlファイル変更時のみ
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SLACK_USERNAME: ci failure notification
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


# go-versionsに書かれているバージョンでビルドとテスト、失敗したらスラックに通知
jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Build
        run: go build -v ./...

      - name: Slack Failure Notification on Build step
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_TITLE: sjrw-build / Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: sjrw build failed!!!

  test:
    needs: build

    strategy:
      matrix:
        go-versions: [1.23.0]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 5

    steps:
      - name: Go Test
        run: go test -v .

      - name: Go Benchmark
        run:  go test -bench . -benchmem

      - name: Slack Failure Notification test 
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
            SLACK_TITLE: sjrw-test / Failure
            SLACK_COLOR: danger
            SLACK_MESSAGE: sjrw test failed!!!