name: ci-SJRW

on:
  push:
    branches: [ main ]
    paths: ['go/**/*go'] # goファイル変更時のみ
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SLACK_USERNAME: ci failure notification
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


# go-versionsに書かれているバージョンでビルドとテスト、失敗したらスラックに通知
jobs:
  ci:
    strategy:
          matrix:
            go-versions: [1.21.0, 1.22.0, 1.23.0]
            os: [ubuntu-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}

      - name: Go Version
        run: go version

      - name: Go Build
        run: go build -v ./...

      - name: Go Test
        run: go test -v .

      - name: Go Benchmark
        run:  go test -bench . -benchmem

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
            SLACK_TITLE: CI / Failure
            SLACK_COLOR: danger
            SLACK_MESSAGE: ci failed!!!