name: ci-SJRW

on:
　　push:
     branches: [ main ]
   workflow_dispatch:

env:
  SLACK_USERNAME: ci failure notification
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        strategy:
          matrix:
           gover: [1.19.0, 1.20.x, 1.21.x, 1.22.x, 1.23.0]

        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.gover}}

      - name: Go Version
        run: go version

      - name: Go Build
        run: |
          go build -v ./...

      - name: Go Test
        run: go test -v *_test.go


      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
            SLACK_TITLE: CI / Failure
            SLACK_COLOR: danger
            SLACK_MESSAGE: ci failed!!!