name: lint with reviewdog

on:
  push:
    branches: [main]

jobs:
  lint:
    strategy:
      matrix:
        go-versions: [1.21.0, 1.22.0, 1.23.0]
        os: [ubuntu-latest]

    permissions:
      checks: write
      contents: read
      pull-requests: write

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go lint with reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: ${{matrix.go-versions}}

          # reviewdog の動作モードの指定
          reporter: github-pr-review

          github_token: ${{github.token}}

          filter_mode: nofilter

          #このファイルパスにgolangciの設定ymlファイルをおく
          golangci_lint_flags: "--config=.golangci.toml"

          # Github Status へのレポートレベルの指定
          level: warning