name: lint with reviewdog

on: push
  branches: [main]

jobs:
  lint:
    permissins:
      checks: write
      contents: read
      pull-request: write
    runs-on: ubuntu-latest
    steps:
      - name: Go lint with reviewdog
      - uses: actions/checkout@v4
      - uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: 1.23.0
          # reviewdog の動作モードの指定
          reporter: github-pr-review

          github_token: ${{github.token}}

          filter_mode: nofilter
          #このファイルパスにgolangciの設定ymlファイルをおく
          golangci_lint_flags: "--config=.golangci.toml"

          # Github Status へのレポートレベルの指定
          level: warning